version: '3'

services:

  web:
   image: nginx:latest
   restart: always
   depends_on:
    - php
    - db
   ports:
   - "8081:80"
   volumes:
   - ./:/ApiTest
   - ./default.conf:/etc/nginx/conf.d/default.conf
   links:
   - php

  php:
    image: php:7.2-fpm
#    build:
#     context: ./
#     dockerfile: Dockerfile
    restart: always
    volumes:
    - ./:/ApiTest
    links:
      - db

  db:
    image: mysql:5.7
    volumes:
    - ./:/ApiTest
    - ./testavito.sql:/ApiTest/docker-entrypoint-initdb.d
    restart: always
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 377377588
    command: --init-file /ApiTest/testavito.sql
